# Generated by Django 3.1.4 on 2020-12-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='Категория'),
        ),
    ]
